# Generated by Django 4.2.4 on 2023-08-24 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)])),
                ('user_image', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images')),
                ('user_details', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
