# Generated by Django 4.2.4 on 2023-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0002_forumuser_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='user_details',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='user_image',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images'),
        ),
    ]
